"use client";

import { FormEvent, useRef, useState } from "react";
import { buildRequest, FieldErrors, FormValues, halfCPower, normalizeApiError, resolveInvestments, SurfaceForm, tariffNeedsManual, validateForm } from "@/lib/pv-economics";
import styles from "./pv-economics-form.module.css";

const states = [["BW","Baden-Württemberg"],["BY","Bayern"],["BE","Berlin"],["BB","Brandenburg"],["HB","Bremen"],["HH","Hamburg"],["HE","Hessen"],["MV","Mecklenburg-Vorpommern"],["NI","Niedersachsen"],["NW","Nordrhein-Westfalen"],["RP","Rheinland-Pfalz"],["SL","Saarland"],["SN","Sachsen"],["ST","Sachsen-Anhalt"],["SH","Schleswig-Holstein"],["TH","Thüringen"]];
const months = ["Januar","Februar","März","April","Mai","Juni","Juli","August","September","Oktober","November","Dezember"];
const matrix = () => Array.from({length: 12}, () => Array(24).fill("0"));
const surface = (n: number): SurfaceForm => ({ key: crypto.randomUUID(), identifier: `Teilfläche ${n}`, peakPower: "8", azimuth: "180", tilt: "30", inverterEfficiency: "96", systemLoss: "14", maxAcPower: "", shadingMode: "constant", constantShading: "0", shadingMatrix: matrix() });
const initial: FormValues = { annualConsumption:"4000", federalState:"", commissioningDate:"2026-06-01", latitude:"51.1657", longitude:"10.4515", profileKind:"h25", surfaces:[surface(1)], batteryEnabled:false, batteryCapacity:"8", batteryRte:"90", chargePower:"4", dischargePower:"4", chargeAutomatic:true, dischargeAutomatic:true, warrantyModel:false, warrantyYears:"10", residualCapacity:"80", warrantyLimitKind:"throughput", warrantedThroughput:"30000", warrantedEfc:"4000", electricityPrice:"35", investments:{pv:"",battery:"",package:""}, manualTariff:"", years:"20", pvDegradation:"0.5", batteryDegradation:"2", electricityGrowth:"2", operatingCostGrowth:"2", discountRate:"3", pvOperatingCost:"", pvOperatingCostAutomatic:true, batteryOperatingCost:"0", postEegValue:"0", feedInLimitKind:"none", feedInLimit:"", feedInLimitYears:"" };

type Result = { metadata?: Record<string, unknown>; warnings?: Array<Record<string, unknown>> };
const inputNumber = { type: "number", step: "any", inputMode: "decimal" as const };

export function PVEconomicsForm() {
  const [v,setV] = useState<FormValues>(initial), [errors,setErrors] = useState<FieldErrors>({}), [apiErrors,setApiErrors] = useState<string[]>([]);
  const [busy,setBusy] = useState(false), [result,setResult] = useState<Result|null>(null); const summary = useRef<HTMLDivElement>(null);
  const set = <K extends keyof FormValues>(key: K, value: FormValues[K]) => setV(x => ({...x,[key]:value}));
  const err = (key:string) => errors[key] ? <span className={styles.error} id={`${key}-error`}>{errors[key]}</span> : null;
  const field = (key:string,label:string,value:string,onChange:(x:string)=>void,unit?:string,props:Record<string,unknown>={}) => <label className={styles.field}><span>{label}{unit && <small> {unit}</small>}</span><input {...inputNumber} {...props} value={value} onChange={e=>onChange(e.target.value)} aria-invalid={!!errors[key]} aria-describedby={errors[key]?`${key}-error`:undefined}/>{err(key)}</label>;
  const updateSurface = (i:number, patch:Partial<SurfaceForm>) => set("surfaces",v.surfaces.map((s,n)=>n===i?{...s,...patch}:s));

  const updateInvestments = (investments: FormValues["investments"], batteryEnabled = v.batteryEnabled) => {
    const pv = resolveInvestments(investments,batteryEnabled).pv;
    setV(x=>({...x,investments,batteryEnabled,pvOperatingCost:x.pvOperatingCostAutomatic?(pv===null?"":String(Math.round(pv)/100)):x.pvOperatingCost}));
  };

  const changeCapacity = (capacity:string) => setV(x=>({...x,batteryCapacity:capacity,chargePower:x.chargeAutomatic?halfCPower(capacity):x.chargePower,dischargePower:x.dischargeAutomatic?halfCPower(capacity):x.dischargePower}));
  async function submit(event:FormEvent) {
    event.preventDefault(); setResult(null); setApiErrors([]); const found=validateForm(v); setErrors(found);
    if(Object.keys(found).length){ setTimeout(()=>summary.current?.focus(),0); return; }
    setBusy(true); try { const response=await fetch("/api/pv-economics/calculate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(buildRequest(v))}); const body:unknown=await response.json().catch(()=>null); if(!response.ok){setApiErrors(normalizeApiError(response.status,body));setTimeout(()=>summary.current?.focus(),0);} else setResult(body as Result); } catch { setApiErrors(normalizeApiError(503,null)); setTimeout(()=>summary.current?.focus(),0); } finally { setBusy(false); }
  }
  const allErrors=[...Object.values(errors),...apiErrors];
  const resolvedInvestment=resolveInvestments(v.investments,v.batteryEnabled);
  const enteredInvestments=[v.investments.pv,v.batteryEnabled?v.investments.battery:"",v.investments.package].filter(x=>x.trim()!=="").length;
  return <section className={`section ${styles.section}`}><form className="shell" onSubmit={submit} noValidate>
    {allErrors.length>0&&<div ref={summary} tabIndex={-1} role="alert" className={styles.summary}><h2>Bitte prüfe deine Eingaben</h2><ul>{allErrors.map((x,i)=><li key={`${x}-${i}`}>{x}</li>)}</ul></div>}
    <div className={styles.intro}><p>Die Berechnung ist eine Modellrechnung, keine Beratung oder Ertragsgarantie. Wetterjahre, Lastprofil und Preisannahmen beeinflussen das Ergebnis.</p></div>

    <fieldset className={styles.card}><legend>A. Haushalt und Standort</legend><div className={styles.grid}>
      {field("annualConsumption","Jahresstromverbrauch",v.annualConsumption,x=>set("annualConsumption",x),"kWh/Jahr")}
      <label className={styles.field}><span>Bundesland</span><select value={v.federalState} onChange={e=>set("federalState",e.target.value)} aria-invalid={!!errors.federalState} aria-describedby={errors.federalState?"federalState-error":undefined}><option value="">Bitte auswählen</option>{states.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select>{err("federalState")}</label>
      <label className={styles.field}><span>Inbetriebnahmedatum</span><input type="date" value={v.commissioningDate} onChange={e=>set("commissioningDate",e.target.value)} aria-invalid={!!errors.commissioningDate} aria-describedby={errors.commissioningDate?"commissioningDate-error":undefined}/>{err("commissioningDate")}</label>
      {field("latitude","Breitengrad",v.latitude,x=>set("latitude",x))}{field("longitude","Längengrad",v.longitude,x=>set("longitude",x))}
    </div><p className={styles.help}>Koordinaten werden nur für die Wetterabfrage verwendet; PVGIS erhält keine vollständige Adresse.</p>
    <label className={styles.field}><span>Lastprofil</span><select value={v.profileKind} onChange={e=>set("profileKind",e.target.value)}><option value="h25">BDEW H25 (Standard)</option><option value="exergypulse_daytime">ExergyPulse Tagesprofil (synthetisch)</option><option value="exergypulse_evening">ExergyPulse Abendprofil (synthetisch)</option><option value="exergypulse_flatter">ExergyPulse gleichmäßigeres Profil (synthetisch)</option></select></label>
    <p className={styles.help}>ExergyPulse-Profile sind synthetische Modellprofile. Wärmepumpe und Elektroauto werden nicht separat modelliert; ihr Verbrauch kann nur im Jahresverbrauch enthalten sein.</p></fieldset>

    <fieldset className={styles.card}><legend>B. PV-Anlage</legend>{err("surfaces")}{v.surfaces.map((s,i)=><section className={styles.subcard} key={s.key}><div className={styles.subhead}><h2>Teilfläche {i+1}</h2>{i>0&&<button type="button" className={styles.quiet} onClick={()=>set("surfaces",v.surfaces.filter((_,n)=>n!==i))}>Teilfläche entfernen</button>}</div><div className={styles.grid}>
      <label className={styles.field}><span>Bezeichnung</span><input value={s.identifier} maxLength={100} onChange={e=>updateSurface(i,{identifier:e.target.value})} aria-invalid={!!errors[`surfaces.${i}.identifier`]} aria-describedby={errors[`surfaces.${i}.identifier`]?`surfaces.${i}.identifier-error`:undefined}/>{err(`surfaces.${i}.identifier`)}</label>
      {field(`surfaces.${i}.peakPower`,"Leistung",s.peakPower,x=>updateSurface(i,{peakPower:x}),"kWp")}{field(`surfaces.${i}.azimuth`,"Ausrichtung / Azimut",s.azimuth,x=>updateSurface(i,{azimuth:x}),"°")}{field(`surfaces.${i}.tilt`,"Neigung",s.tilt,x=>updateSurface(i,{tilt:x}),"°")}{field(`surfaces.${i}.constantShading`,"Pauschale Verschattung",s.constantShading,x=>updateSurface(i,{constantShading:x}),"%",{disabled:s.shadingMode==="matrix"})}
    </div><p className={styles.help}>Azimut: 0° = Nord, 90° = Ost, 180° = Süd, 270° = West.</p>
    <details className={styles.details}><summary>Technik und Verschattung (Expertenmodus)</summary><div className={styles.grid}>{field(`surfaces.${i}.inverterEfficiency`,"Wechselrichterwirkungsgrad",s.inverterEfficiency,x=>updateSurface(i,{inverterEfficiency:x}),"%")}{field(`surfaces.${i}.systemLoss`,"Systemverluste",s.systemLoss,x=>updateSurface(i,{systemLoss:x}),"%")}{field(`surfaces.${i}.maxAcPower`,"Maximale AC-Leistung (optional)",s.maxAcPower,x=>updateSurface(i,{maxAcPower:x}),"kW")}</div>
      <fieldset className={styles.inner}><legend>Verschattungsmodell</legend><label><input type="radio" name={`shading-${s.key}`} checked={s.shadingMode==="constant"} onChange={()=>updateSurface(i,{shadingMode:"constant"})}/> Pauschaler Wert</label><label><input type="radio" name={`shading-${s.key}`} checked={s.shadingMode==="matrix"} onChange={()=>updateSurface(i,{shadingMode:"matrix"})}/> 12 × 24-Matrix</label></fieldset>
      {s.shadingMode==="matrix"&&<ShadingMatrix surface={s} index={i} update={updateSurface} errors={errors}/>}<p className={styles.help}>Verschattung vermindert im Modell nur den direkten Strahlungsanteil.</p>
    </details></section>)}<button type="button" className={styles.add} onClick={()=>set("surfaces",[...v.surfaces,surface(v.surfaces.length+1)])}>Weitere Teilfläche hinzufügen</button></fieldset>

    <fieldset className={styles.card}><legend>C. Speicher</legend><label className={styles.toggle}><input type="checkbox" checked={v.batteryEnabled} onChange={e=>updateInvestments(v.investments,e.target.checked)}/> Heimspeicher in den Vergleich aufnehmen</label>{v.batteryEnabled&&<><div className={styles.grid}>{field("batteryCapacity","Nutzbare Kapazität",v.batteryCapacity,changeCapacity,"kWh")}{field("batteryRte","Round-Trip-Wirkungsgrad",v.batteryRte,x=>set("batteryRte",x),"%")}{field("chargePower","Ladeleistung",v.chargePower,x=>setV(y=>({...y,chargePower:x,chargeAutomatic:false})),"kW")}{field("dischargePower","Entladeleistung",v.dischargePower,x=>setV(y=>({...y,dischargePower:x,dischargeAutomatic:false})),"kW")}</div><p className={styles.help}>Standard: 90 % Wirkungsgrad und 0,5C für Laden und Entladen. Automatische 0,5C-Werte folgen der Kapazität; manuell geänderte Leistungen bleiben erhalten.</p>
      <details className={styles.details}><summary>Garantie-Degradationsmodell (Expertenmodus)</summary><label className={styles.toggle}><input type="checkbox" checked={v.warrantyModel} onChange={e=>set("warrantyModel",e.target.checked)}/> Garantiegrenzen statt pauschaler Degradation verwenden</label>{v.warrantyModel&&<><div className={styles.grid}>{field("warrantyYears","Garantiezeit",v.warrantyYears,x=>set("warrantyYears",x),"Jahre")}{field("residualCapacity","Garantierte Restkapazität",v.residualCapacity,x=>set("residualCapacity",x),"%")}</div><fieldset className={styles.inner}><legend>Genau eine Garantiegrenze</legend><label><input type="radio" name="warranty-limit" checked={v.warrantyLimitKind==="throughput"} onChange={()=>set("warrantyLimitKind","throughput")}/> Durchsatz</label><label><input type="radio" name="warranty-limit" checked={v.warrantyLimitKind==="efc"} onChange={()=>set("warrantyLimitKind","efc")}/> Vollzyklen (EFC)</label></fieldset>{v.warrantyLimitKind==="throughput"?field("warrantedThroughput","Garantierter Durchsatz",v.warrantedThroughput,x=>set("warrantedThroughput",x),"kWh"):field("warrantedEfc","Garantierte Vollzyklen",v.warrantedEfc,x=>set("warrantedEfc",x),"EFC")}<p className={styles.help}>Das sind Garantiegrenzen des Herstellers, keine erwartete Prognose.</p></>}</details></>}</fieldset>

    <fieldset className={styles.card}><legend>D. Preise und Investition</legend><div className={styles.grid}>{field("electricityPrice","Aktueller Strompreis",v.electricityPrice,x=>set("electricityPrice",x),"ct/kWh")}{field("investments.pv","PV-Preis",v.investments.pv,x=>updateInvestments({...v.investments,pv:x}),"€")}{v.batteryEnabled&&field("investments.battery","Speichermehrpreis",v.investments.battery,x=>updateInvestments({...v.investments,battery:x}),"€")}{field("investments.package","Paketpreis",v.investments.package,x=>updateInvestments({...v.investments,package:x}),"€")}{field("manualTariff","Manuelle Einspeisevergütung",v.manualTariff,x=>set("manualTariff",x),"ct/kWh")}</div>{err("investments")}<p className={styles.help}>Paketpreis = PV-Preis + Speichermehrpreis. Bei genau zwei Angaben wird die dritte abgeleitet. Nur der Paketpreis ist ebenfalls zulässig; er wird nicht künstlich aufgeteilt.</p>{enteredInvestments===2&&!resolvedInvestment.error&&<p className={styles.resolution}>Aufgelöst für die Berechnung: PV {resolvedInvestment.pv?.toLocaleString("de-DE") ?? "–"} €, Speicher {resolvedInvestment.battery?.toLocaleString("de-DE") ?? "–"} €, Paket {resolvedInvestment.package?.toLocaleString("de-DE") ?? "–"} €.</p>}{tariffNeedsManual(v.commissioningDate)&&<p className={styles.warning}>Für Inbetriebnahmen außerhalb 01.02.2026 bis 31.07.2026 ist eine manuelle Einspeisevergütung erforderlich.</p>}</fieldset>

    <details className={`${styles.card} ${styles.details}`}><summary>E. Expertenannahmen</summary><p className={styles.help}>Keine automatischen Ersatzinvestitionen. Alle Prozentwerte gelten pro Jahr.</p><div className={styles.grid}>{field("years","Betrachtungszeitraum",v.years,x=>set("years",x),"Jahre")}{field("pvDegradation","PV-Degradation",v.pvDegradation,x=>set("pvDegradation",x),"% p. a.")}{field("batteryDegradation","Speicherdegradation",v.batteryDegradation,x=>set("batteryDegradation",x),"% p. a.")}{field("electricityGrowth","Strompreissteigerung",v.electricityGrowth,x=>set("electricityGrowth",x),"% p. a.")}{field("operatingCostGrowth","Betriebskostensteigerung",v.operatingCostGrowth,x=>set("operatingCostGrowth",x),"% p. a.")}{field("discountRate","Nominaler Diskontsatz",v.discountRate,x=>set("discountRate",x),"% p. a.")}{field("pvOperatingCost","PV-Betriebskosten Jahr 1",v.pvOperatingCost,x=>setV(y=>({...y,pvOperatingCost:x,pvOperatingCostAutomatic:false})),"€")}{field("batteryOperatingCost","Speicherbetriebskosten Jahr 1",v.batteryOperatingCost,x=>set("batteryOperatingCost",x),"€")}{field("postEegValue","Wert nach EEG-Ende",v.postEegValue,x=>set("postEegValue",x),"€/kWh")}</div><p className={styles.help}>{resolveInvestments(v.investments,v.batteryEnabled).pv===null?"Bei reinem Paketpreis bleibt die PV-Kostenaufteilung unbekannt; es erfolgt keine künstliche Aufteilung. PV- und Speicher-Investitionskennzahlen sind deshalb nur eingeschränkt verfügbar. Die jährlichen PV-Betriebskosten müssen ausdrücklich angegeben werden.":"Der angezeigte Standard für PV-Betriebskosten beträgt 1 % der aufgelösten PV-Investition pro Jahr."}</p>
      <fieldset className={styles.inner}><legend>Optionale Einspeisebegrenzung</legend><select value={v.feedInLimitKind} onChange={e=>set("feedInLimitKind",e.target.value as FormValues["feedInLimitKind"])}><option value="none">Keine</option><option value="kw">In kW</option><option value="percent">In Prozent</option></select>{v.feedInLimitKind!=="none"&&<div className={styles.grid}>{field("feedInLimit","Grenzwert",v.feedInLimit,x=>set("feedInLimit",x),v.feedInLimitKind==="kw"?"kW":"%")}{field("feedInLimitYears","Betroffene Jahre",v.feedInLimitYears,x=>set("feedInLimitYears",x),"Jahre")}</div>}</fieldset></details>

    <div className={styles.submit}><button className="button button-primary" type="submit" disabled={busy}>{busy?"Berechnung läuft …":"Konfiguration berechnen"}</button>{busy&&<p role="status">Wetterabruf und Stundensimulation können etwas dauern. Bitte lass diese Seite geöffnet.</p>}</div>
    {result&&<section className={styles.success} aria-live="polite"><h2>Berechnung abgeschlossen</h2><Metadata data={result.metadata}/><p>{result.warnings?.length ? `${result.warnings.length} Warnung(en): ${result.warnings.map(w=>String(w.message||w.code||"Hinweis")).slice(0,3).join("; ")}`:"Keine Warnungen in der Antwort."}</p><p>Die ausführliche Ergebnisdarstellung entsteht im folgenden Arbeitspaket.</p></section>}
  </form></section>;
}

function ShadingMatrix({surface,index,update,errors}:{surface:SurfaceForm;index:number;update:(i:number,p:Partial<SurfaceForm>)=>void;errors:FieldErrors}) { return <div className={styles.matrixWrap}><table><caption>Verschattung in Prozent nach Monat und lokaler Stunde</caption><thead><tr><th scope="col">Monat</th>{Array.from({length:24},(_,h)=><th scope="col" key={h}>{h}:00</th>)}</tr></thead><tbody>{surface.shadingMatrix.map((row,m)=><tr key={m}><th scope="row">{months[m]}</th>{row.map((cell,h)=><td key={h}><input type="number" min="0" max="100" step="any" aria-label={`${months[m]}, ${h}:00 Uhr`} aria-invalid={!!errors[`surfaces.${index}.matrix.${m}.${h}`]} value={cell} onChange={e=>{const next=surface.shadingMatrix.map(r=>[...r]);next[m][h]=e.target.value;update(index,{shadingMatrix:next});}}/></td>)}</tr>)}</tbody></table></div> }
function Metadata({data}:{data?:Record<string,unknown>}) { if(!data)return <p>Kein Modell-/Datenstand übermittelt.</p>; const entries=Object.entries(data).filter(([,x])=>["string","number"].includes(typeof x)).slice(0,5); return entries.length?<dl className={styles.metadata}>{entries.map(([k,x])=><div key={k}><dt>{k.replaceAll("_"," ")}</dt><dd>{String(x)}</dd></div>)}</dl>:<p>Modell-/Datenstand ist in den Metadaten enthalten.</p> }
